#!/bin/bash

BASEDIR=$(dirname "$0")

java -cp "$BASEDIR/projects/joern-fuzzyc/build/libs/joern-fuzzyc.jar:$BASEDIR/projects/joern-common/build/libs/joern-common.jar:$BASEDIR/jars/*" tools.parser.ParserMain $@
