#!/usr/bin/env python3

from octopus.shelltool.ChunkStartTool import ChunkStartTool

DESCRIPTION = """Create a list of all functions of the code base. The
first field is the function's name, the second field is the id of the
corresponding node in the database, and the third is the file it is
contained in"""

class ListFuncs(ChunkStartTool):

      def __init__(self, DESCRIPTION):
            ChunkStartTool.__init__(self, DESCRIPTION)

            self.argParser.add_argument('-p', '--pattern',
                                        action = 'store', type=str,
                                        default =".*")

      def _constructIdQuery(self):
            return """
            g.V.has(NODE_TYPE,TYPE_FUNCTION)
            .has(NODE_CODE, textRegex('%s')).id
            """ % (self.args.pattern)

      def _constructQueryForChunk(self, chunk):
            return """idListToNodes(%s).as('func')
            .functionToFile().as('file')
            .select('func','file')
            .map{ it['func'].id + '\t' + it['func'].code + '\t' + it['file'].code }
            """ % (chunk)

      def _handleChunkResult(self, res, chunk):
            for x in res:
                  print(x)


if __name__ == '__main__':
      tool = ListFuncs(DESCRIPTION)
      tool.run()
