// Generated from src/antlr/Function.g4 by ANTLR 4.0.1-SNAPSHOT

	package antlr;


  import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.ErrorNode;
import org.antlr.v4.runtime.tree.TerminalNode;

public class FunctionBaseListener implements FunctionListener {
	@Override public void enterPre_else(FunctionParser.Pre_elseContext ctx) { }
	@Override public void exitPre_else(FunctionParser.Pre_elseContext ctx) { }
	@Override public void enterDeclarator(FunctionParser.DeclaratorContext ctx) { }
	@Override public void exitDeclarator(FunctionParser.DeclaratorContext ctx) { }
	@Override public void enterTemplate_decl_start(FunctionParser.Template_decl_startContext ctx) { }
	@Override public void exitTemplate_decl_start(FunctionParser.Template_decl_startContext ctx) { }
	@Override public void enterFunction_argument_list(FunctionParser.Function_argument_listContext ctx) { }
	@Override public void exitFunction_argument_list(FunctionParser.Function_argument_listContext ctx) { }
	@Override public void enterType_suffix(FunctionParser.Type_suffixContext ctx) { }
	@Override public void exitType_suffix(FunctionParser.Type_suffixContext ctx) { }
	@Override public void enterNo_squares_or_semicolon(FunctionParser.No_squares_or_semicolonContext ctx) { }
	@Override public void exitNo_squares_or_semicolon(FunctionParser.No_squares_or_semicolonContext ctx) { }
	@Override public void enterFor_statement(FunctionParser.For_statementContext ctx) { }
	@Override public void exitFor_statement(FunctionParser.For_statementContext ctx) { }
	@Override public void enterCast_expression(FunctionParser.Cast_expressionContext ctx) { }
	@Override public void exitCast_expression(FunctionParser.Cast_expressionContext ctx) { }
	@Override public void enterNo_angle_brackets_or_brackets(FunctionParser.No_angle_brackets_or_bracketsContext ctx) { }
	@Override public void exitNo_angle_brackets_or_brackets(FunctionParser.No_angle_brackets_or_bracketsContext ctx) { }
	@Override public void enterEquality_expression(FunctionParser.Equality_expressionContext ctx) { }
	@Override public void exitEquality_expression(FunctionParser.Equality_expressionContext ctx) { }
	@Override public void enterNo_comma_or_semicolon(FunctionParser.No_comma_or_semicolonContext ctx) { }
	@Override public void exitNo_comma_or_semicolon(FunctionParser.No_comma_or_semicolonContext ctx) { }
	@Override public void enterTry_statement(FunctionParser.Try_statementContext ctx) { }
	@Override public void exitTry_statement(FunctionParser.Try_statementContext ctx) { }
	@Override public void enterNumber(FunctionParser.NumberContext ctx) { }
	@Override public void exitNumber(FunctionParser.NumberContext ctx) { }
	@Override public void enterBase_type(FunctionParser.Base_typeContext ctx) { }
	@Override public void exitBase_type(FunctionParser.Base_typeContext ctx) { }
	@Override public void enterPtrMemberAccess(FunctionParser.PtrMemberAccessContext ctx) { }
	@Override public void exitPtrMemberAccess(FunctionParser.PtrMemberAccessContext ctx) { }
	@Override public void enterPre_opener(FunctionParser.Pre_openerContext ctx) { }
	@Override public void exitPre_opener(FunctionParser.Pre_openerContext ctx) { }
	@Override public void enterNo_squares(FunctionParser.No_squaresContext ctx) { }
	@Override public void exitNo_squares(FunctionParser.No_squaresContext ctx) { }
	@Override public void enterShift_expression(FunctionParser.Shift_expressionContext ctx) { }
	@Override public void exitShift_expression(FunctionParser.Shift_expressionContext ctx) { }
	@Override public void enterDeclByClass(FunctionParser.DeclByClassContext ctx) { }
	@Override public void exitDeclByClass(FunctionParser.DeclByClassContext ctx) { }
	@Override public void enterType_name(FunctionParser.Type_nameContext ctx) { }
	@Override public void exitType_name(FunctionParser.Type_nameContext ctx) { }
	@Override public void enterBreakStatement(FunctionParser.BreakStatementContext ctx) { }
	@Override public void exitBreakStatement(FunctionParser.BreakStatementContext ctx) { }
	@Override public void enterFuncCall(FunctionParser.FuncCallContext ctx) { }
	@Override public void exitFuncCall(FunctionParser.FuncCallContext ctx) { }
	@Override public void enterInclusive_or_expression(FunctionParser.Inclusive_or_expressionContext ctx) { }
	@Override public void exitInclusive_or_expression(FunctionParser.Inclusive_or_expressionContext ctx) { }
	@Override public void enterBase_classes(FunctionParser.Base_classesContext ctx) { }
	@Override public void exitBase_classes(FunctionParser.Base_classesContext ctx) { }
	@Override public void enterIncDecOp(FunctionParser.IncDecOpContext ctx) { }
	@Override public void exitIncDecOp(FunctionParser.IncDecOpContext ctx) { }
	@Override public void enterPre_closer(FunctionParser.Pre_closerContext ctx) { }
	@Override public void exitPre_closer(FunctionParser.Pre_closerContext ctx) { }
	@Override public void enterRelational_expression(FunctionParser.Relational_expressionContext ctx) { }
	@Override public void exitRelational_expression(FunctionParser.Relational_expressionContext ctx) { }
	@Override public void enterClass_name(FunctionParser.Class_nameContext ctx) { }
	@Override public void exitClass_name(FunctionParser.Class_nameContext ctx) { }
	@Override public void enterParam_decl_specifiers(FunctionParser.Param_decl_specifiersContext ctx) { }
	@Override public void exitParam_decl_specifiers(FunctionParser.Param_decl_specifiersContext ctx) { }
	@Override public void enterParam_type(FunctionParser.Param_typeContext ctx) { }
	@Override public void exitParam_type(FunctionParser.Param_typeContext ctx) { }
	@Override public void enterFunction_argument(FunctionParser.Function_argumentContext ctx) { }
	@Override public void exitFunction_argument(FunctionParser.Function_argumentContext ctx) { }
	@Override public void enterIf_statement(FunctionParser.If_statementContext ctx) { }
	@Override public void exitIf_statement(FunctionParser.If_statementContext ctx) { }
	@Override public void enterWater(FunctionParser.WaterContext ctx) { }
	@Override public void exitWater(FunctionParser.WaterContext ctx) { }
	@Override public void enterClosing_curly(FunctionParser.Closing_curlyContext ctx) { }
	@Override public void exitClosing_curly(FunctionParser.Closing_curlyContext ctx) { }
	@Override public void enterFor_init_statement(FunctionParser.For_init_statementContext ctx) { }
	@Override public void exitFor_init_statement(FunctionParser.For_init_statementContext ctx) { }
	@Override public void enterOr_expression(FunctionParser.Or_expressionContext ctx) { }
	@Override public void exitOr_expression(FunctionParser.Or_expressionContext ctx) { }
	@Override public void enterRelational_operator(FunctionParser.Relational_operatorContext ctx) { }
	@Override public void exitRelational_operator(FunctionParser.Relational_operatorContext ctx) { }
	@Override public void enterDo_statement1(FunctionParser.Do_statement1Context ctx) { }
	@Override public void exitDo_statement1(FunctionParser.Do_statement1Context ctx) { }
	@Override public void enterOperator(FunctionParser.OperatorContext ctx) { }
	@Override public void exitOperator(FunctionParser.OperatorContext ctx) { }
	@Override public void enterInc_dec(FunctionParser.Inc_decContext ctx) { }
	@Override public void exitInc_dec(FunctionParser.Inc_decContext ctx) { }
	@Override public void enterConditional_expression(FunctionParser.Conditional_expressionContext ctx) { }
	@Override public void exitConditional_expression(FunctionParser.Conditional_expressionContext ctx) { }
	@Override public void enterInitDeclSimple(FunctionParser.InitDeclSimpleContext ctx) { }
	@Override public void exitInitDeclSimple(FunctionParser.InitDeclSimpleContext ctx) { }
	@Override public void enterOpening_curly(FunctionParser.Opening_curlyContext ctx) { }
	@Override public void exitOpening_curly(FunctionParser.Opening_curlyContext ctx) { }
	@Override public void enterPrimary_expression(FunctionParser.Primary_expressionContext ctx) { }
	@Override public void exitPrimary_expression(FunctionParser.Primary_expressionContext ctx) { }
	@Override public void enterGotoStatement(FunctionParser.GotoStatementContext ctx) { }
	@Override public void exitGotoStatement(FunctionParser.GotoStatementContext ctx) { }
	@Override public void enterNo_brackets(FunctionParser.No_bracketsContext ctx) { }
	@Override public void exitNo_brackets(FunctionParser.No_bracketsContext ctx) { }
	@Override public void enterBit_and_expression(FunctionParser.Bit_and_expressionContext ctx) { }
	@Override public void exitBit_and_expression(FunctionParser.Bit_and_expressionContext ctx) { }
	@Override public void enterAssign_water(FunctionParser.Assign_waterContext ctx) { }
	@Override public void exitAssign_water(FunctionParser.Assign_waterContext ctx) { }
	@Override public void enterCast_target(FunctionParser.Cast_targetContext ctx) { }
	@Override public void exitCast_target(FunctionParser.Cast_targetContext ctx) { }
	@Override public void enterInitializer(FunctionParser.InitializerContext ctx) { }
	@Override public void exitInitializer(FunctionParser.InitializerContext ctx) { }
	@Override public void enterFunction_decl_specifiers(FunctionParser.Function_decl_specifiersContext ctx) { }
	@Override public void exitFunction_decl_specifiers(FunctionParser.Function_decl_specifiersContext ctx) { }
	@Override public void enterReturnStatement(FunctionParser.ReturnStatementContext ctx) { }
	@Override public void exitReturnStatement(FunctionParser.ReturnStatementContext ctx) { }
	@Override public void enterMultiplicative_expression(FunctionParser.Multiplicative_expressionContext ctx) { }
	@Override public void exitMultiplicative_expression(FunctionParser.Multiplicative_expressionContext ctx) { }
	@Override public void enterAssign_expr(FunctionParser.Assign_exprContext ctx) { }
	@Override public void exitAssign_expr(FunctionParser.Assign_exprContext ctx) { }
	@Override public void enterExpr_statement(FunctionParser.Expr_statementContext ctx) { }
	@Override public void exitExpr_statement(FunctionParser.Expr_statementContext ctx) { }
	@Override public void enterMemberAccess(FunctionParser.MemberAccessContext ctx) { }
	@Override public void exitMemberAccess(FunctionParser.MemberAccessContext ctx) { }
	@Override public void enterBase_class(FunctionParser.Base_classContext ctx) { }
	@Override public void exitBase_class(FunctionParser.Base_classContext ctx) { }
	@Override public void enterParameter_name(FunctionParser.Parameter_nameContext ctx) { }
	@Override public void exitParameter_name(FunctionParser.Parameter_nameContext ctx) { }
	@Override public void enterAccess_specifier(FunctionParser.Access_specifierContext ctx) { }
	@Override public void exitAccess_specifier(FunctionParser.Access_specifierContext ctx) { }
	@Override public void enterAssign_water_l2(FunctionParser.Assign_water_l2Context ctx) { }
	@Override public void exitAssign_water_l2(FunctionParser.Assign_water_l2Context ctx) { }
	@Override public void enterInit_declarator_list(FunctionParser.Init_declarator_listContext ctx) { }
	@Override public void exitInit_declarator_list(FunctionParser.Init_declarator_listContext ctx) { }
	@Override public void enterCondition(FunctionParser.ConditionContext ctx) { }
	@Override public void exitCondition(FunctionParser.ConditionContext ctx) { }
	@Override public void enterArrayIndexing(FunctionParser.ArrayIndexingContext ctx) { }
	@Override public void exitArrayIndexing(FunctionParser.ArrayIndexingContext ctx) { }
	@Override public void enterCatch_statement(FunctionParser.Catch_statementContext ctx) { }
	@Override public void exitCatch_statement(FunctionParser.Catch_statementContext ctx) { }
	@Override public void enterLabel(FunctionParser.LabelContext ctx) { }
	@Override public void exitLabel(FunctionParser.LabelContext ctx) { }
	@Override public void enterExclusive_or_expression(FunctionParser.Exclusive_or_expressionContext ctx) { }
	@Override public void exitExclusive_or_expression(FunctionParser.Exclusive_or_expressionContext ctx) { }
	@Override public void enterStatement(FunctionParser.StatementContext ctx) { }
	@Override public void exitStatement(FunctionParser.StatementContext ctx) { }
	@Override public void enterInitDeclWithCall(FunctionParser.InitDeclWithCallContext ctx) { }
	@Override public void exitInitDeclWithCall(FunctionParser.InitDeclWithCallContext ctx) { }
	@Override public void enterParam_type_id(FunctionParser.Param_type_idContext ctx) { }
	@Override public void exitParam_type_id(FunctionParser.Param_type_idContext ctx) { }
	@Override public void enterAdditive_expression(FunctionParser.Additive_expressionContext ctx) { }
	@Override public void exitAdditive_expression(FunctionParser.Additive_expressionContext ctx) { }
	@Override public void enterInitializer_list(FunctionParser.Initializer_listContext ctx) { }
	@Override public void exitInitializer_list(FunctionParser.Initializer_listContext ctx) { }
	@Override public void enterUnary_operator(FunctionParser.Unary_operatorContext ctx) { }
	@Override public void exitUnary_operator(FunctionParser.Unary_operatorContext ctx) { }
	@Override public void enterElse_statement(FunctionParser.Else_statementContext ctx) { }
	@Override public void exitElse_statement(FunctionParser.Else_statementContext ctx) { }
	@Override public void enterSwitch_statement(FunctionParser.Switch_statementContext ctx) { }
	@Override public void exitSwitch_statement(FunctionParser.Switch_statementContext ctx) { }
	@Override public void enterDo_statement(FunctionParser.Do_statementContext ctx) { }
	@Override public void exitDo_statement(FunctionParser.Do_statementContext ctx) { }
	@Override public void enterNo_brackets_curlies_or_squares(FunctionParser.No_brackets_curlies_or_squaresContext ctx) { }
	@Override public void exitNo_brackets_curlies_or_squares(FunctionParser.No_brackets_curlies_or_squaresContext ctx) { }
	@Override public void enterWhile_statement(FunctionParser.While_statementContext ctx) { }
	@Override public void exitWhile_statement(FunctionParser.While_statementContext ctx) { }
	@Override public void enterIdentifier(FunctionParser.IdentifierContext ctx) { }
	@Override public void exitIdentifier(FunctionParser.IdentifierContext ctx) { }
	@Override public void enterPrimaryOnly(FunctionParser.PrimaryOnlyContext ctx) { }
	@Override public void exitPrimaryOnly(FunctionParser.PrimaryOnlyContext ctx) { }
	@Override public void enterNo_brackets_or_semicolon(FunctionParser.No_brackets_or_semicolonContext ctx) { }
	@Override public void exitNo_brackets_or_semicolon(FunctionParser.No_brackets_or_semicolonContext ctx) { }
	@Override public void enterNo_curlies(FunctionParser.No_curliesContext ctx) { }
	@Override public void exitNo_curlies(FunctionParser.No_curliesContext ctx) { }
	@Override public void enterEquality_operator(FunctionParser.Equality_operatorContext ctx) { }
	@Override public void exitEquality_operator(FunctionParser.Equality_operatorContext ctx) { }
	@Override public void enterExpr(FunctionParser.ExprContext ctx) { }
	@Override public void exitExpr(FunctionParser.ExprContext ctx) { }
	@Override public void enterParam_type_list(FunctionParser.Param_type_listContext ctx) { }
	@Override public void exitParam_type_list(FunctionParser.Param_type_listContext ctx) { }
	@Override public void enterSimple_decl(FunctionParser.Simple_declContext ctx) { }
	@Override public void exitSimple_decl(FunctionParser.Simple_declContext ctx) { }
	@Override public void enterBlock_starter(FunctionParser.Block_starterContext ctx) { }
	@Override public void exitBlock_starter(FunctionParser.Block_starterContext ctx) { }
	@Override public void enterAssignment_operator(FunctionParser.Assignment_operatorContext ctx) { }
	@Override public void exitAssignment_operator(FunctionParser.Assignment_operatorContext ctx) { }
	@Override public void enterStatements(FunctionParser.StatementsContext ctx) { }
	@Override public void exitStatements(FunctionParser.StatementsContext ctx) { }
	@Override public void enterUnary_expression(FunctionParser.Unary_expressionContext ctx) { }
	@Override public void exitUnary_expression(FunctionParser.Unary_expressionContext ctx) { }
	@Override public void enterPtrs(FunctionParser.PtrsContext ctx) { }
	@Override public void exitPtrs(FunctionParser.PtrsContext ctx) { }
	@Override public void enterInitDeclWithAssign(FunctionParser.InitDeclWithAssignContext ctx) { }
	@Override public void exitInitDeclWithAssign(FunctionParser.InitDeclWithAssignContext ctx) { }
	@Override public void enterConstant(FunctionParser.ConstantContext ctx) { }
	@Override public void exitConstant(FunctionParser.ConstantContext ctx) { }
	@Override public void enterContinueStatement(FunctionParser.ContinueStatementContext ctx) { }
	@Override public void exitContinueStatement(FunctionParser.ContinueStatementContext ctx) { }
	@Override public void enterPtr_operator(FunctionParser.Ptr_operatorContext ctx) { }
	@Override public void exitPtr_operator(FunctionParser.Ptr_operatorContext ctx) { }
	@Override public void enterClass_def(FunctionParser.Class_defContext ctx) { }
	@Override public void exitClass_def(FunctionParser.Class_defContext ctx) { }
	@Override public void enterAnd_expression(FunctionParser.And_expressionContext ctx) { }
	@Override public void exitAnd_expression(FunctionParser.And_expressionContext ctx) { }
	@Override public void enterTemplate_param_list(FunctionParser.Template_param_listContext ctx) { }
	@Override public void exitTemplate_param_list(FunctionParser.Template_param_listContext ctx) { }
	@Override public void enterDeclByType(FunctionParser.DeclByTypeContext ctx) { }
	@Override public void exitDeclByType(FunctionParser.DeclByTypeContext ctx) { }

	@Override public void enterEveryRule(ParserRuleContext<? extends Token> ctx) { }
	@Override public void exitEveryRule(ParserRuleContext<? extends Token> ctx) { }
	@Override public void visitTerminal(TerminalNode<? extends Token> node) { }
	@Override public void visitErrorNode(ErrorNode<? extends Token> node) { }
}