// Generated from src/antlr/Module.g4 by ANTLR 4.0.1-SNAPSHOT

	package antlr;


  import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.ErrorNode;
import org.antlr.v4.runtime.tree.TerminalNode;

public class ModuleBaseListener implements ModuleListener {
	@Override public void enterDeclarator(ModuleParser.DeclaratorContext ctx) { }
	@Override public void exitDeclarator(ModuleParser.DeclaratorContext ctx) { }
	@Override public void enterTemplate_decl_start(ModuleParser.Template_decl_startContext ctx) { }
	@Override public void exitTemplate_decl_start(ModuleParser.Template_decl_startContext ctx) { }
	@Override public void enterFunction_decl_specifiers(ModuleParser.Function_decl_specifiersContext ctx) { }
	@Override public void exitFunction_decl_specifiers(ModuleParser.Function_decl_specifiersContext ctx) { }
	@Override public void enterType_suffix(ModuleParser.Type_suffixContext ctx) { }
	@Override public void exitType_suffix(ModuleParser.Type_suffixContext ctx) { }
	@Override public void enterFunction_argument_list(ModuleParser.Function_argument_listContext ctx) { }
	@Override public void exitFunction_argument_list(ModuleParser.Function_argument_listContext ctx) { }
	@Override public void enterMultiplicative_expression(ModuleParser.Multiplicative_expressionContext ctx) { }
	@Override public void exitMultiplicative_expression(ModuleParser.Multiplicative_expressionContext ctx) { }
	@Override public void enterCompound_statement(ModuleParser.Compound_statementContext ctx) { }
	@Override public void exitCompound_statement(ModuleParser.Compound_statementContext ctx) { }
	@Override public void enterNo_squares_or_semicolon(ModuleParser.No_squares_or_semicolonContext ctx) { }
	@Override public void exitNo_squares_or_semicolon(ModuleParser.No_squares_or_semicolonContext ctx) { }
	@Override public void enterAssign_expr(ModuleParser.Assign_exprContext ctx) { }
	@Override public void exitAssign_expr(ModuleParser.Assign_exprContext ctx) { }
	@Override public void enterCast_expression(ModuleParser.Cast_expressionContext ctx) { }
	@Override public void exitCast_expression(ModuleParser.Cast_expressionContext ctx) { }
	@Override public void enterNo_angle_brackets_or_brackets(ModuleParser.No_angle_brackets_or_bracketsContext ctx) { }
	@Override public void exitNo_angle_brackets_or_brackets(ModuleParser.No_angle_brackets_or_bracketsContext ctx) { }
	@Override public void enterEquality_expression(ModuleParser.Equality_expressionContext ctx) { }
	@Override public void exitEquality_expression(ModuleParser.Equality_expressionContext ctx) { }
	@Override public void enterParameter_decl_clause(ModuleParser.Parameter_decl_clauseContext ctx) { }
	@Override public void exitParameter_decl_clause(ModuleParser.Parameter_decl_clauseContext ctx) { }
	@Override public void enterNo_comma_or_semicolon(ModuleParser.No_comma_or_semicolonContext ctx) { }
	@Override public void exitNo_comma_or_semicolon(ModuleParser.No_comma_or_semicolonContext ctx) { }
	@Override public void enterMemberAccess(ModuleParser.MemberAccessContext ctx) { }
	@Override public void exitMemberAccess(ModuleParser.MemberAccessContext ctx) { }
	@Override public void enterBase_class(ModuleParser.Base_classContext ctx) { }
	@Override public void exitBase_class(ModuleParser.Base_classContext ctx) { }
	@Override public void enterFunction_name(ModuleParser.Function_nameContext ctx) { }
	@Override public void exitFunction_name(ModuleParser.Function_nameContext ctx) { }
	@Override public void enterParameter_name(ModuleParser.Parameter_nameContext ctx) { }
	@Override public void exitParameter_name(ModuleParser.Parameter_nameContext ctx) { }
	@Override public void enterCtor_list(ModuleParser.Ctor_listContext ctx) { }
	@Override public void exitCtor_list(ModuleParser.Ctor_listContext ctx) { }
	@Override public void enterAccess_specifier(ModuleParser.Access_specifierContext ctx) { }
	@Override public void exitAccess_specifier(ModuleParser.Access_specifierContext ctx) { }
	@Override public void enterCtor_expr(ModuleParser.Ctor_exprContext ctx) { }
	@Override public void exitCtor_expr(ModuleParser.Ctor_exprContext ctx) { }
	@Override public void enterInit_declarator_list(ModuleParser.Init_declarator_listContext ctx) { }
	@Override public void exitInit_declarator_list(ModuleParser.Init_declarator_listContext ctx) { }
	@Override public void enterAssign_water_l2(ModuleParser.Assign_water_l2Context ctx) { }
	@Override public void exitAssign_water_l2(ModuleParser.Assign_water_l2Context ctx) { }
	@Override public void enterInit_declarator(ModuleParser.Init_declaratorContext ctx) { }
	@Override public void exitInit_declarator(ModuleParser.Init_declaratorContext ctx) { }
	@Override public void enterArrayIndexing(ModuleParser.ArrayIndexingContext ctx) { }
	@Override public void exitArrayIndexing(ModuleParser.ArrayIndexingContext ctx) { }
	@Override public void enterParameter_decl(ModuleParser.Parameter_declContext ctx) { }
	@Override public void exitParameter_decl(ModuleParser.Parameter_declContext ctx) { }
	@Override public void enterNumber(ModuleParser.NumberContext ctx) { }
	@Override public void exitNumber(ModuleParser.NumberContext ctx) { }
	@Override public void enterBase_type(ModuleParser.Base_typeContext ctx) { }
	@Override public void exitBase_type(ModuleParser.Base_typeContext ctx) { }
	@Override public void enterReturn_type(ModuleParser.Return_typeContext ctx) { }
	@Override public void exitReturn_type(ModuleParser.Return_typeContext ctx) { }
	@Override public void enterCode(ModuleParser.CodeContext ctx) { }
	@Override public void exitCode(ModuleParser.CodeContext ctx) { }
	@Override public void enterCtor_initializer(ModuleParser.Ctor_initializerContext ctx) { }
	@Override public void exitCtor_initializer(ModuleParser.Ctor_initializerContext ctx) { }
	@Override public void enterExclusive_or_expression(ModuleParser.Exclusive_or_expressionContext ctx) { }
	@Override public void exitExclusive_or_expression(ModuleParser.Exclusive_or_expressionContext ctx) { }
	@Override public void enterAssign_expr_w_(ModuleParser.Assign_expr_w_Context ctx) { }
	@Override public void exitAssign_expr_w_(ModuleParser.Assign_expr_w_Context ctx) { }
	@Override public void enterParam_type_id(ModuleParser.Param_type_idContext ctx) { }
	@Override public void exitParam_type_id(ModuleParser.Param_type_idContext ctx) { }
	@Override public void enterPtrMemberAccess(ModuleParser.PtrMemberAccessContext ctx) { }
	@Override public void exitPtrMemberAccess(ModuleParser.PtrMemberAccessContext ctx) { }
	@Override public void enterInitializer_list(ModuleParser.Initializer_listContext ctx) { }
	@Override public void exitInitializer_list(ModuleParser.Initializer_listContext ctx) { }
	@Override public void enterAdditive_expression(ModuleParser.Additive_expressionContext ctx) { }
	@Override public void exitAdditive_expression(ModuleParser.Additive_expressionContext ctx) { }
	@Override public void enterUnary_operator(ModuleParser.Unary_operatorContext ctx) { }
	@Override public void exitUnary_operator(ModuleParser.Unary_operatorContext ctx) { }
	@Override public void enterNo_squares(ModuleParser.No_squaresContext ctx) { }
	@Override public void exitNo_squares(ModuleParser.No_squaresContext ctx) { }
	@Override public void enterDeclByClass(ModuleParser.DeclByClassContext ctx) { }
	@Override public void exitDeclByClass(ModuleParser.DeclByClassContext ctx) { }
	@Override public void enterShift_expression(ModuleParser.Shift_expressionContext ctx) { }
	@Override public void exitShift_expression(ModuleParser.Shift_expressionContext ctx) { }
	@Override public void enterType_name(ModuleParser.Type_nameContext ctx) { }
	@Override public void exitType_name(ModuleParser.Type_nameContext ctx) { }
	@Override public void enterNo_brackets_curlies_or_squares(ModuleParser.No_brackets_curlies_or_squaresContext ctx) { }
	@Override public void exitNo_brackets_curlies_or_squares(ModuleParser.No_brackets_curlies_or_squaresContext ctx) { }
	@Override public void enterIdentifier(ModuleParser.IdentifierContext ctx) { }
	@Override public void exitIdentifier(ModuleParser.IdentifierContext ctx) { }
	@Override public void enterFuncCall(ModuleParser.FuncCallContext ctx) { }
	@Override public void exitFuncCall(ModuleParser.FuncCallContext ctx) { }
	@Override public void enterPrimaryOnly(ModuleParser.PrimaryOnlyContext ctx) { }
	@Override public void exitPrimaryOnly(ModuleParser.PrimaryOnlyContext ctx) { }
	@Override public void enterInclusive_or_expression(ModuleParser.Inclusive_or_expressionContext ctx) { }
	@Override public void exitInclusive_or_expression(ModuleParser.Inclusive_or_expressionContext ctx) { }
	@Override public void enterFunction_param_list(ModuleParser.Function_param_listContext ctx) { }
	@Override public void exitFunction_param_list(ModuleParser.Function_param_listContext ctx) { }
	@Override public void enterNo_brackets_or_semicolon(ModuleParser.No_brackets_or_semicolonContext ctx) { }
	@Override public void exitNo_brackets_or_semicolon(ModuleParser.No_brackets_or_semicolonContext ctx) { }
	@Override public void enterBase_classes(ModuleParser.Base_classesContext ctx) { }
	@Override public void exitBase_classes(ModuleParser.Base_classesContext ctx) { }
	@Override public void enterIncDecOp(ModuleParser.IncDecOpContext ctx) { }
	@Override public void exitIncDecOp(ModuleParser.IncDecOpContext ctx) { }
	@Override public void enterEquality_operator(ModuleParser.Equality_operatorContext ctx) { }
	@Override public void exitEquality_operator(ModuleParser.Equality_operatorContext ctx) { }
	@Override public void enterNo_curlies(ModuleParser.No_curliesContext ctx) { }
	@Override public void exitNo_curlies(ModuleParser.No_curliesContext ctx) { }
	@Override public void enterParam_type_list(ModuleParser.Param_type_listContext ctx) { }
	@Override public void exitParam_type_list(ModuleParser.Param_type_listContext ctx) { }
	@Override public void enterExpr(ModuleParser.ExprContext ctx) { }
	@Override public void exitExpr(ModuleParser.ExprContext ctx) { }
	@Override public void enterClass_name(ModuleParser.Class_nameContext ctx) { }
	@Override public void exitClass_name(ModuleParser.Class_nameContext ctx) { }
	@Override public void enterRelational_expression(ModuleParser.Relational_expressionContext ctx) { }
	@Override public void exitRelational_expression(ModuleParser.Relational_expressionContext ctx) { }
	@Override public void enterSimple_decl(ModuleParser.Simple_declContext ctx) { }
	@Override public void exitSimple_decl(ModuleParser.Simple_declContext ctx) { }
	@Override public void enterParam_decl_specifiers(ModuleParser.Param_decl_specifiersContext ctx) { }
	@Override public void exitParam_decl_specifiers(ModuleParser.Param_decl_specifiersContext ctx) { }
	@Override public void enterAssignment_operator(ModuleParser.Assignment_operatorContext ctx) { }
	@Override public void exitAssignment_operator(ModuleParser.Assignment_operatorContext ctx) { }
	@Override public void enterParam_type(ModuleParser.Param_typeContext ctx) { }
	@Override public void exitParam_type(ModuleParser.Param_typeContext ctx) { }
	@Override public void enterType_id_list(ModuleParser.Type_id_listContext ctx) { }
	@Override public void exitType_id_list(ModuleParser.Type_id_listContext ctx) { }
	@Override public void enterFunction_argument(ModuleParser.Function_argumentContext ctx) { }
	@Override public void exitFunction_argument(ModuleParser.Function_argumentContext ctx) { }
	@Override public void enterUnary_expression(ModuleParser.Unary_expressionContext ctx) { }
	@Override public void exitUnary_expression(ModuleParser.Unary_expressionContext ctx) { }
	@Override public void enterPtrs(ModuleParser.PtrsContext ctx) { }
	@Override public void exitPtrs(ModuleParser.PtrsContext ctx) { }
	@Override public void enterConstant_expr_w_(ModuleParser.Constant_expr_w_Context ctx) { }
	@Override public void exitConstant_expr_w_(ModuleParser.Constant_expr_w_Context ctx) { }
	@Override public void enterWater(ModuleParser.WaterContext ctx) { }
	@Override public void exitWater(ModuleParser.WaterContext ctx) { }
	@Override public void enterOr_expression(ModuleParser.Or_expressionContext ctx) { }
	@Override public void exitOr_expression(ModuleParser.Or_expressionContext ctx) { }
	@Override public void enterConstant(ModuleParser.ConstantContext ctx) { }
	@Override public void exitConstant(ModuleParser.ConstantContext ctx) { }
	@Override public void enterAssign_expr_w__l2(ModuleParser.Assign_expr_w__l2Context ctx) { }
	@Override public void exitAssign_expr_w__l2(ModuleParser.Assign_expr_w__l2Context ctx) { }
	@Override public void enterFunction_def(ModuleParser.Function_defContext ctx) { }
	@Override public void exitFunction_def(ModuleParser.Function_defContext ctx) { }
	@Override public void enterUsing_directive(ModuleParser.Using_directiveContext ctx) { }
	@Override public void exitUsing_directive(ModuleParser.Using_directiveContext ctx) { }
	@Override public void enterRelational_operator(ModuleParser.Relational_operatorContext ctx) { }
	@Override public void exitRelational_operator(ModuleParser.Relational_operatorContext ctx) { }
	@Override public void enterPtr_operator(ModuleParser.Ptr_operatorContext ctx) { }
	@Override public void exitPtr_operator(ModuleParser.Ptr_operatorContext ctx) { }
	@Override public void enterOperator(ModuleParser.OperatorContext ctx) { }
	@Override public void exitOperator(ModuleParser.OperatorContext ctx) { }
	@Override public void enterClass_def(ModuleParser.Class_defContext ctx) { }
	@Override public void exitClass_def(ModuleParser.Class_defContext ctx) { }
	@Override public void enterInitializer_id(ModuleParser.Initializer_idContext ctx) { }
	@Override public void exitInitializer_id(ModuleParser.Initializer_idContext ctx) { }
	@Override public void enterInc_dec(ModuleParser.Inc_decContext ctx) { }
	@Override public void exitInc_dec(ModuleParser.Inc_decContext ctx) { }
	@Override public void enterConditional_expression(ModuleParser.Conditional_expressionContext ctx) { }
	@Override public void exitConditional_expression(ModuleParser.Conditional_expressionContext ctx) { }
	@Override public void enterAnd_expression(ModuleParser.And_expressionContext ctx) { }
	@Override public void exitAnd_expression(ModuleParser.And_expressionContext ctx) { }
	@Override public void enterPrimary_expression(ModuleParser.Primary_expressionContext ctx) { }
	@Override public void exitPrimary_expression(ModuleParser.Primary_expressionContext ctx) { }
	@Override public void enterException_specification(ModuleParser.Exception_specificationContext ctx) { }
	@Override public void exitException_specification(ModuleParser.Exception_specificationContext ctx) { }
	@Override public void enterTemplate_param_list(ModuleParser.Template_param_listContext ctx) { }
	@Override public void exitTemplate_param_list(ModuleParser.Template_param_listContext ctx) { }
	@Override public void enterDeclByType(ModuleParser.DeclByTypeContext ctx) { }
	@Override public void exitDeclByType(ModuleParser.DeclByTypeContext ctx) { }
	@Override public void enterParameter_id(ModuleParser.Parameter_idContext ctx) { }
	@Override public void exitParameter_id(ModuleParser.Parameter_idContext ctx) { }
	@Override public void enterNo_brackets(ModuleParser.No_bracketsContext ctx) { }
	@Override public void exitNo_brackets(ModuleParser.No_bracketsContext ctx) { }
	@Override public void enterBit_and_expression(ModuleParser.Bit_and_expressionContext ctx) { }
	@Override public void exitBit_and_expression(ModuleParser.Bit_and_expressionContext ctx) { }
	@Override public void enterInitializer(ModuleParser.InitializerContext ctx) { }
	@Override public void exitInitializer(ModuleParser.InitializerContext ctx) { }
	@Override public void enterCast_target(ModuleParser.Cast_targetContext ctx) { }
	@Override public void exitCast_target(ModuleParser.Cast_targetContext ctx) { }
	@Override public void enterAssign_water(ModuleParser.Assign_waterContext ctx) { }
	@Override public void exitAssign_water(ModuleParser.Assign_waterContext ctx) { }

	@Override public void enterEveryRule(ParserRuleContext<? extends Token> ctx) { }
	@Override public void exitEveryRule(ParserRuleContext<? extends Token> ctx) { }
	@Override public void visitTerminal(TerminalNode<? extends Token> node) { }
	@Override public void visitErrorNode(ErrorNode<? extends Token> node) { }
}