#!/usr/bin/env python

from joern.shelltool.LookupTool import LookupTool

DESCRIPTION = """Lookup nodes using lucene queries and output one row
for each matching node. Rows are in the format functionId TAB
attributeKey:attributeValue TAB ...'
"""

if __name__ == '__main__':
    tool = LookupTool(DESCRIPTION)
    tool.run()
